### ISSUE TITLE
Gem won't work in Pd-0.51-4 Next

### ISSUE THREAD

**Issue by MikeMorenoDSP** [sebshader/pdnext#3]
Hello,

First, thanks Seb for saving my eyes, the background color trick in Pd-0.51 isn't working anymore, so I resorted to Pd-next.
Long overdue for me, but it is amazing.

So, Gem loads fine, and I can create objects, but it won't let gemwin create a window, don't know why.
It works fine with regular pd vanilla 0.51-4.

When I try to create a window appears on the console:

[gemmacoswindow]: failed to init GLEW: your system only supports openGL-1.0
[gemmacoswindow]: unable to switch to current window (do you have one?), cannot render!

Any clues?
Thanks again! :)

**Comment by sebshader** [comment]
Hi @MikeMorenoDSP. Unfortunately, Pd vanilla compiled on my system (OSX 10.14.6) has this issue as well. It must have to do with the newer vs. older MacOs compiler/command line tools somehow.

I've run into this issue before with Gem I compiled myself as well, as have others (can't remember if it was with Pd compiled myself or not). umlaute/Gem#257 umlaute/Gem#204 umlaute/Gem#263.

It seems like if either Gem or Pd is compiled on a newer mac it will not work. (there are some workarounds in those threads but it sounds like they aren't completely stable)

maybe it has something to do with OSX deprecating OpenGL in mojave..
we might have luck with Pd-next compiled on an older osx platform.. I tried compiling with "-mmacosx-version-min=10.6" and that didn't work..

**Comment by sebshader** [comment]
I managed to compile GEM again and it worked on pd-vanilla, which leads me to believe that it's the OS that pd is compiled with that's the factor, and not the OS that GEM is compiled with. (but it still pretty much has to be fixed in GEM I think)

**Comment by 60-hz** [comment]
Ok great, it compile now ;)

But when I launch pd then I have empty patch, no boxes and this message:

DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.
2021-10-20 23:40:02.844 Wish[44557:1010230] CoreText note: Client requested name ".SFNSMono-Regular", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2021-10-20 23:40:02.844 Wish[44557:1010230] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2021-10-20 23:40:02.845 Wish[44557:1010230] CoreText note: Client requested name ".SF NS Mono", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].

**Comment by sebshader** [comment]
@60-hz I have had many issues with GEM as well (as documented in the issues linked above), I don't think those issues are specific to pd-next though. just any pd compiled on modern osx unfortunately.

**Comment by sebshader** [comment]
@60-hz I think the only practical way would be to compile Pd on an older Mac machine. Seems like Miller uses MacOS 10.9ish?
